Dev 8
ohatsenko/online-bookstore pull request #10
Opened 2023-09-24 14:01 UTC by ohatsenko

2023-09-24 14:50 UTC, ivan0dyatlyukkk approved these changes
GJ!

2023-09-26 12:29 UTC, andrii-hoienko requested changes
GJ, I left minor comments

2023-09-26 12:29 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/model/CartItem.java
> +    private ShoppingCart shoppingCart;
Please make toOne relations lazy

2023-09-26 12:29 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        cartItem.setBook(bookRepository.findById(requestDto.getBookId()).orElseThrow(
Please use book service to get entities via repository

2023-09-26 12:29 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findById(id)
code duplication

2023-09-26 12:29 UTC, andrii-hoienko commented on src/main/java/com/example/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    public CartItemDto save(CreateCartItemRequestDto requestDto, Long id) {
parameter id is super confusing, please rename it

2023-09-26 12:29 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +        file: db/changelog/changes/011-create-shopping-cart-cart-item-table.yaml
add empty line

2023-09-27 12:54 UTC, andrii-hoienko approved these changes
GJ!

2023-09-27 14:57 UTC, merged