added dto, mapstruct and mapper
ohatsenko/online-bookstore pull request #2
Opened 2023-09-05 15:14 UTC by ohatsenko

2023-09-05 18:07 UTC, DmytroV95 requested changes
GJ! Let's improve it!

2023-09-05 18:07 UTC, DmytroV95 commented on pom.xml
> +</project>
No empty line

2023-09-05 18:07 UTC, DmytroV95 commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +    Book getById(Long id);
I think we need to use Optional return type to be sure we will not get NPE if the necessary book is not found.

2023-09-08 14:14 UTC, vovasalyha approved these changes
GJ, take a look on few minor suggestions.

2023-09-08 14:14 UTC, vovasalyha commented on pom.xml
> +            <version>1.18.28</version>
lombok version is provided by parent pom

2023-09-08 14:14 UTC, vovasalyha commented on src/main/java/com/example/onlinebookstore/repository/BookRepository.java
> +    Optional<Book> getById(Long id);
in repositories it's common to name methods `find`
```suggestion
    Optional<Book> findById(Long id);
```

2023-09-08 15:45 UTC, merged